# Generated by Django 2.0.5 on 2018-05-22 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.IntegerField(choices=[(1, 'Area 1'), (2, 'Area 2')])),
                ('tariff', models.IntegerField(choices=[(1, 'Tarriff 1'), (2, 'Tarriff 2'), (3, 'Tarriff 3')])),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date and time of consumption.')),
                ('magnitude', models.FloatField(verbose_name='Amount of energy consumed.')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.Consumer')),
            ],
        ),
    ]
